- name: Start Kafka service
  service:
      name: kafka
      state: started
      enabled: true 

- name: Start Zookeeper service
  service:
      name: zookeeper
      state: started
      enabled: true 